/** İşletme kartlarına eklenen kısa gerçek dünya / Türkiye bağlamı */
export const PRODUCER_LORE: Record<string, string> = {
  stajyer: 'İstanbul\'da her yaz 2 milyon stajyer — imparatorluk böyle başlar.',
  berber: 'Mahalle berberi, Türkiye\'nin en dayanıklı mikro işletmesi.',
  limonata: 'Sıcak yaz günlerinde sokak satıcıları — nakit akışının temeli.',
  kafe: 'Third wave kahve dalgası — Nişantaşı\'ndan Kadıköy\'e.',
  otel: 'Turizm geliri Türkiye GDP\'sinin ~%12\'si; otel zincirleri kral.',
  fabrika: 'Organize sanayi bölgeleri — Kocaeli, Bursa, Gaziantep.',
  holding: 'Koç, Sabancı, Eczacıbaşı — holding modeli Türk kapitalizminin omurgası.',
  banka: 'Türkiye\'de 50+ banka; faiz politikası herkesi etkiler.',
  medya: 'Medya grubu = siyaset + iş dünyası kapısı.',
  futbol: 'Süper Lig TV hakları milyarlarca dolar — stadyum yatırımı stratejik.',
  siyaset: 'Lobi faaliyeti ve bağış — itibarın siyasi boyutu.',
  illegal: 'Radar yükselirse baskın riski — sigorta ve torpil devreye girer.',
  firin: 'Ekmek, Türk mutfağının temel taşı. Fırın zinciri = güvenli nakit akışı.',
  cicekci: 'Türkiye, Hollanda\'dan sonra Avrupa\'nın en büyük çiçek ihracatçısı.',
  giyim: 'Türkiye, dünyanın 5. büyük tekstil ihracatçısı — moda endüstrisi devasa.',
  gym: 'Sağlık bilinci artan Türkiye\'de fitness sektörü yıllık %15 büyüyor.',
  kargo: 'E-ticaret patlamasıyla kargo sektörü milyar dolarlık iş haline geldi.',
  reklam_ajansi: 'Dijital reklam harcamaları geleneksel medyayı geçti — ajanslar altın çağında.',
  insaat: 'İnşaat sektörü Türkiye GDP\'sinin %8\'i. Her şehirde vinç var.',
  hukuk: 'Kurumsal hukuk büroları, uluslararası yatırım dalgasından besleniyor.',
  cikolata: 'Türk çikolata sektörü yıllık $1.5B ihracat yapıyor — Ülker lider.',
  pet_shop: 'Evcil hayvan sahipliği %40 artış gösterdi; premium ürünler patlıyor.',
  oyun_studio: 'Türk oyun şirketleri 2023\'te $1B+ ihracat yaptı — Dream Games, Peak öncü.',
  temizlik: 'Facility management sektörü AVM ve ofis patlamasıyla büyüdü.',
  emlak_ofis: 'İstanbul\'da metrekare başına en pahalı kentlerden; emlakçı kritik köprü.',
  hastane: 'Özel sağlık sektörü devlet hastanesinin önüne geçti — sağlık turizmi bonus.',
  universite: 'Özel üniversite sayısı 80\'i geçti; eğitime talep hiç durmadı.',
  havayolu: 'THY, dünyanın en fazla ülkeye uçan havayolu — İstanbul hub stratejik.',
  liman: 'Türkiye\'nin 5 kıtaya ulaşan coğrafyası limanları altın değerinde yapıyor.',
  ruzgar: 'Rüzgar kapasitesi 11 GW\'ı aştı — yenilenebilir enerji süratle büyüyor.',
  maden: 'Türkiye, bor rezervlerinin %73\'üne sahip — stratejik maden gücü.',
  nukleer: 'Akkuyu Nükleer Santrali 2026 devreye giriyor — enerji bağımsızlığı hedefi.',
  tarim_tek: 'AgriTech startupları geleneksel tarımı dijitalleştiriyor — verim +40%.',
  yacht_filo: 'Bodrum ve Marmaris, küresel superyacht destinasyonu haline geldi.',
  formula1: 'Formula 1 takımı kurmak $500M+ yatırım gerektiriyor ama prestiç sonsuz.',
  casino_legal: 'Online kumarhane sektörü küresel $100B+ — lisanslı pazar çok değerli.',
  adalar: 'Özel ada sahipliği, ultra-HNW (ultra yüksek servetli) grubun statü sembolü.',
  saat_marka: 'Lüks saat satışları 2023\'te $10B\'a ulaştı — Türkiye\'den alıcı patladı.',
  jet_filo: 'Özel jet kullanımı pandemi sonrası %200 arttı — havacılık lüksü normalleşiyor.',
  banka_ozel: 'Private banking, $1M+ müşterilere özel bankacılık — ücret yok, getiri var.',
  hedge_fund: 'Hedge fonlar volatil piyasalarda yüksek getiri arıyor — risk yönetimi sanat.',
  kripto: 'Türkiye, kripto kullanım oranında dünya 5.\'si — genç nüfus öncü.',
  nft_borsa: 'Dijital varlık piyasası 2024\'te toparlandı — altyapı sağlayıcılar kazanıyor.',
  kuyumcu: 'Türkiye, dünyanın 4. büyük altın tüketicisi — kuyumcu sektörü dev.',
  telekom: 'Mobil penetrasyon %110\'u aştı — 5G yarışı süperlik için kritik.',
  borsa_araci: 'BIST 100 günlük işlem hacmi $1B+ — aracı kurum komisyonları birikir.',
  biyotek: 'CRISPR ve gen terapisi 2030\'da $200B+ pazar olacak — erken giren kazanır.',
  uzay_istasyonu: 'Uzay ekonomisi 2040\'a kadar $1 trilyon büyüklüğüne ulaşacak.',
  kuantum: 'Kuantum bilgisayarlar kriptografi ve ilaç geliştirmeyi kökten değiştirecek.',
  fuzyon: 'Füzyon enerjisi — sınırsız temiz enerji. Gerçekleşirse oyun değişir.',
  mars: 'SpaceX ve Blue Origin Mars yarışında — ilk koloni milyarderlerin eseri olacak.',
}

export function producerLore(producerId: string): string | null {
  return PRODUCER_LORE[producerId] ?? null
}
