-- Supabase genişletme: arkadaş LB + oyuncu kimliği
-- SQL Editor'da çalıştırın (mevcut game_leaderboard tablosuna kolon ekler)

ALTER TABLE game_leaderboard
  ADD COLUMN IF NOT EXISTS player_id text,
  ADD COLUMN IF NOT EXISTS friend_code text;

CREATE INDEX IF NOT EXISTS idx_game_leaderboard_friend_code ON game_leaderboard (friend_code);
CREATE INDEX IF NOT EXISTS idx_game_leaderboard_player_id ON game_leaderboard (player_id);

-- Opsiyonel: arkadaşlık tablosu (ileride sunucu tarafı doğrulama için)
CREATE TABLE IF NOT EXISTS game_friendships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id text NOT NULL,
  friend_code text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE game_leaderboard ENABLE ROW LEVEL SECURITY;
-- Anon insert/select politikalarını projenize göre ayarlayın
