-- Supabase genişletme: arkadaş LB + oyuncu kimliği
-- SQL Editor'da çalıştırın (mevcut game_leaderboard tablosuna kolon ekler)

ALTER TABLE game_leaderboard
  ADD COLUMN IF NOT EXISTS player_id text,
  ADD COLUMN IF NOT EXISTS friend_code text;

CREATE UNIQUE INDEX IF NOT EXISTS idx_game_leaderboard_player_id_unique ON game_leaderboard (player_id) WHERE player_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_game_leaderboard_friend_code ON game_leaderboard (friend_code);
CREATE INDEX IF NOT EXISTS idx_game_leaderboard_lifetime ON game_leaderboard (lifetime_earned DESC);

CREATE TABLE IF NOT EXISTS game_friendships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id text NOT NULL,
  friend_code text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE game_leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_friendships ENABLE ROW LEVEL SECURITY;

-- Anon: skor okuma (herkese açık sıralama)
DROP POLICY IF EXISTS leaderboard_select_anon ON game_leaderboard;
CREATE POLICY leaderboard_select_anon ON game_leaderboard
  FOR SELECT TO anon
  USING (true);

-- Anon: kendi skorunu upsert (player_id ile)
DROP POLICY IF EXISTS leaderboard_insert_anon ON game_leaderboard;
CREATE POLICY leaderboard_insert_anon ON game_leaderboard
  FOR INSERT TO anon
  WITH CHECK (player_id IS NOT NULL AND length(player_id) >= 8);

DROP POLICY IF EXISTS leaderboard_update_anon ON game_leaderboard;
CREATE POLICY leaderboard_update_anon ON game_leaderboard
  FOR UPDATE TO anon
  USING (player_id IS NOT NULL)
  WITH CHECK (player_id IS NOT NULL);

-- Arkadaş tablosu: okuma/yazma (basit — prod'da auth ile sıkılaştırın)
DROP POLICY IF EXISTS friendships_all_anon ON game_friendships;
CREATE POLICY friendships_all_anon ON game_friendships
  FOR ALL TO anon
  USING (true)
  WITH CHECK (true);
